# Generated by Django 2.1.1 on 2018-10-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocktests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=30, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to=questions.models.upload_location_choices)),
                ('thumbnail', models.FileField(editable=False, upload_to='thumbs')),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockTestSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_no', models.IntegerField()),
                ('sentence_text', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=questions.models.upload_location_sentence)),
                ('thumbnail', models.FileField(editable=False, upload_to='thumbs')),
                ('audio', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('mocktestsubsection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSubSection')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', tinymce.models.HTMLField()),
                ('hint', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=questions.models.upload_location)),
                ('thumbnail', models.FileField(editable=False, upload_to='thumbs')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('mocktestsentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.MockTestSentence')),
                ('mocktestsubsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSubSection')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.Attempt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
