# Generated by Django 2.1.1 on 2018-10-23 15:26

import audiofield.fields
from django.db import migrations
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181023_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to=questions.models.upload_location_audio),
        ),
    ]
