# Generated by Django 2.1.1 on 2018-10-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import programs.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', tinymce.models.HTMLField()),
                ('description', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=programs.models.upload_location)),
                ('thumbnail', models.FileField(editable=False, upload_to='thumbs')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('enrolled', models.ManyToManyField(blank=True, through='programs.Enrollment', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reviewprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ReviewProgram'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
