# Generated by Django 2.1.1 on 2018-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1),
        ),
    ]
