# Generated by Django 2.1.1 on 2018-10-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('totalitems', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'CANCELLED'), (1, 'ONGOING'), (2, 'FINISHED')], default=1)),
                ('attempt_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('overview', tinymce.models.HTMLField()),
                ('guidelines', tinymce.models.HTMLField()),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted', to=settings.AUTH_USER_MODEL)),
                ('reviewprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ReviewProgram')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(null=True)),
                ('description', tinymce.models.HTMLField()),
                ('guidelines', tinymce.models.HTMLField()),
                ('test_time_minutes', models.TimeField()),
                ('max_no_of_attempts', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTest')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('guidelines', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('mocktestsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSection')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('totalitems', models.IntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.Attempt')),
                ('mocktestsubsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSubSection')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='mocktestsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSection'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
