# Generated by Django 2.1.1 on 2018-10-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0006_attempt_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestsection',
            name='passing_mark',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
